#############################################################################
# Generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#  Jun 13, 2019 03:50:56 PM PDT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1053x733+478+136
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 5124 1036
    wm minsize $top 133 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "BlueOS"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m45
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men46" -activebackground {#ececec} \
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label File 
    menu $site_3_0.men46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {Tahoma 8} -foreground black -tearoff 0 
    $site_3_0.men46 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#save} -font TkMenuFont \
        -foreground {#000000} -label Save 
    $site_3_0.men46 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#load} -font TkMenuFont \
        -foreground {#000000} -label Load 
    $site_3_0.men46 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#import_project} -font TkMenuFont \
        -foreground {#000000} -label Import 
    $site_3_0.men46 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#project_settings} -font TkMenuFont \
        -foreground {#000000} -label {Project Settings} 
    $site_3_0 add cascade \
        -menu "$site_3_0.men46" -activebackground {#ececec} \
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label File -menu "$site_3_0.men47" \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -label Edit 
    menu $site_3_0.men47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {Tahoma 8} -foreground black -tearoff 0 
    $site_3_0.men47 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -label NewCommand 
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font "TkDefaultFont"
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo48 \
        -width 1053 -height 759 -takefocus {} 
    vTcl:DefineAlias "$top.tNo48" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo48.t0 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t0" "TNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t0 \
        -padding 0 -sticky nsew -state normal -text Processor -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo48.t0
    listbox $site_4_0.lis49 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 9} -foreground {#000000} \
        -height 713 -highlightbackground {#d9d9d9} -highlightcolor black \
        -relief flat -selectbackground {#c4c4c4} -selectforeground black \
        -width 334 
    .top42.tNo48.t0.lis49 configure -font "-family {Courier New} -size 9"
    .top42.tNo48.t0.lis49 insert end text
    vTcl:DefineAlias "$site_4_0.lis49" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    canvas $site_4_0.can51 \
        -background {#dff9fc} -borderwidth 1 -closeenough 1.0 -height 713 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 313 
    vTcl:DefineAlias "$site_4_0.can51" "Canvas2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.can51 <ButtonRelease-1> {
        lambda e: C2_Button1(e)
    }
    canvas $site_4_0.can52 \
        -background {#dff9fc} -borderwidth 1 -closeenough 1.0 -height 713 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 373 
    vTcl:DefineAlias "$site_4_0.can52" "Canvas3" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.can52 <ButtonRelease-1> {
        lambda e: C3_Button1(e)
    }
    place $site_4_0.lis49 \
        -in $site_4_0 -x 710 -y 10 -width 334 -relwidth 0 -height 713 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.can51 \
        -in $site_4_0 -x 10 -y 10 -width 313 -relwidth 0 -height 713 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.can52 \
        -in $site_4_0 -x 330 -y 10 -width 373 -relwidth 0 -height 713 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo48.t1 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t1" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t1 \
        -padding 0 -sticky nsew -state normal -text Tasks -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo48.t1
    canvas $site_4_1.can49 \
        -background {#dff9fc} -borderwidth 1 -closeenough 1.0 -height 693 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 1033 
    vTcl:DefineAlias "$site_4_1.can49" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_1.can49 <ButtonRelease-1> {
        lambda e: C1_Button1(e)
    }
    place $site_4_1.can49 \
        -in $site_4_1 -x 6 -y 6 -width 1035 -relwidth 0 -height 695 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo48 \
        -in $top -x 0 -y 0 -width 1053 -relwidth 0 -height 759 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

